### ISSUE TITLE
Could not run on Latest Version 4.0.0

### ISSUE THREAD

**Issue by leochung042** [temyers/cucumber-jvm-parallel-plugin#107]
Dear 

I copy the content of Usage section into my pom.xml file.

run: **mvn clean install**
then the following error showing, I have tried and looked for solution, but I couldn't find it.

Please help and give me some hint

BTW, I was using version 1.2.1 which run well.

thank you,
Leo

**Error Msg:**
> [ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners (generateRunners) on project cucumber-web: Unable to parse configuration of mojo com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners for parameter plugin: Cannot find 'plugin' in class com.github.timm.cucumber.generate.Plugin -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners (generateRunners) on project cucumber-web: Unable to parse configuration of mojo com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners for parameter plugin: Cannot find 'plugin' in class com.github.timm.cucumber.generate.Plugin
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners for parameter plugin: Cannot find 'plugin' in class com.github.timm.cucumber.generate.Plugin
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:662)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:594)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find 'plugin' in class com.github.timm.cucumber.generate.Plugin
	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:252)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:57)
	at org.codehaus.plexus.component.configurator.converters.composite.AbstractCollectionConverter.fromChildren(AbstractCollectionConverter.java:54)
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:68)
	at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty(CompositeBeanHelper.java:268)
	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:210)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:34)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:632)
	... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException

**Comment by leochung042** [comment]
Looks like, if I remove the following from pom.file, then it would be fine.
> 
        <plugins>
            <plugins>
                <plugin>
                    <name>json</name>
                </plugin>
                <plugin>
                    <name>my.other.package.CustomHtmlFormatter</name>
                    <extension>html</extension>
                </plugin>
            </plugins>
        </plugins>

**Comment by leochung042** [comment]
However, if I remove the Cucumber Plugins, then there is another problem that I faced.

The problem related to "featuresDirectory"
Since My features directory structure is like:
src/test/resources/features

                    - folder1
                         - xxx.feature
                         - ......
                    - folder2
                         - sub-folder2-1
                              - xxx.feature
                              - ....
                         - sub-folder2-2
                              - xxx.feature
                              - ....
                    - folder3

When I used version 1.2.1, it was fine, but it is not okay in version 4.0.0, 
in version 4.0.0, the featuresDirectory set as following with my features structure
"<featuresDirectory>src/test/resources/features/</featuresDirectory>"
The error msg:

> [ERROR] Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners (generateRunners) on project cucumber-web: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:4.0.0:generateRunners failed: Parser errors:
[ERROR] (31:0): unexpected end of file, expected: #Language, #TagLine, #FeatureLine, #Comment, #Empty

in version 4.0.0, the featuresDirectory set as following with my features structure
"<featuresDirectory>src/test/resources/features/folder1/</featuresDirectory>"
then it is fine.

Please help me up, whether I set anything wrong.

Thank you,
Leo

**Comment by mpkorstanje** [comment]
What is described as:

```xml
<plugins>
    <plugins>
        <plugin>
            <name>json</name>
        </plugin>
        <plugin>
            <name>my.other.package.CustomHtmlFormatter</name>
            <extension>html</extension>
        </plugin>
    </plugins>
</plugins>```

Has one level of `</plugins>` to many and should be:

```xml
<plugins>
        <plugin>
            <name>json</name>
        </plugin>
        <plugin>
            <name>my.other.package.CustomHtmlFormatter</name>
            <extension>html</extension>
        </plugin>
</plugins>
```

**Comment by leochung042** [comment]
@mpkorstanje  thank you for your reply.
Yes, it works as you said having one level of <plugins>.

Thank you,
Leo

**Comment by mpkorstanje** [comment]
@leochung042 I can't quite reproduce your second issue can you run your maven command with -X and post the full stacktrace?

**Comment by leochung042** [comment]
@mpkorstanje   Thank you for helping.

I found the issue, since there is one feature file which has been comment out all file. 

So after I removed the file, everything is fine.

Sorry to trouble you.

I am going to mark as close.

Thank you,
Leo
